# Site settings
title: Albert Valencia | Data Analyst
description: Data Analyst specializing in Python, SQL, and ML-driven insights with 3+ years of experience in competitive intelligence and predictive analytics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsalvalenci.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Albert Valencia
user_description: Data Analyst with 3+ years in competitive intelligence and predictive analytics. Specializing in Python, SQL, and ML-driven insights for operations and market trends. Improved operational efficiency by more than 30% at Odoo Inc via ETL automation and cross-functional collaboration.
user_title: Data Analyst | San Francisco, CA
email: albertvalencia904@gmail.com
twitter_username: itsalvalenci
github_username: ItsAlValenci

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
