# Site settings
title: Albert Valencia | Portfolio
description: Senior Data Analyst with over 5 years of experience helping businesses understand their data and make better decisions. Skilled at turning complex information into clear, practical solutions that drive real results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsalvalenci.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ALBERT VALENCIA
user_description: 
  <p>Over the past five years, I’ve worked across a variety of industries, allowing me to combine technical expertise with real-world business insight in every project. Beyond my data role, I’ve gained experience in project management, product ownership, and quality assurance, all of which have enhanced my ability to collaborate effectively across teams and approach challenges from multiple angles.</p>

  <p>I’ve found that being adaptable and comfortable with ambiguity has been one of my biggest strengths. I enjoy taking messy, incomplete, or complex data problems and breaking them down into clear, practical solutions that get implemented. Whether it’s translating technical findings into insights that shape business strategy, designing models that address user needs, or collaborating with teams to define and prioritize challenges, I focus on finding the middle ground between data and business to move projects forward and drive meaningful results.</p>

  <p>Outside of work, I’ve been passionate about video games for over a decade. I volunteer as a playtester for different games and software (mostly for the fun of it) because I like seeing how people actually use and react to different systems. It’s shown me how even small changes can completely reshape the way people interact with and experience a product.</p>

user_title: Sr. Data Analyst | San Francisco, CA
email: line.albertval@gmail.com
twitter_username: ItsAlValenci
github_username: ItsAlValenci

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# bundle exec jekyll build
